### ISSUE TITLE
Error during the first connection

### ISSUE THREAD

**Issue by mackermann2** [BGmot/zabbix#1]
Hello, 

I get this error message (on the connection panel) only when the user authenticates the first time on Zabbix (v4.4.4) : 
**Field "userid" cannot be set to NULL** 

Remark: all the next connections work without any error messages.

**Comment by BGmot** [comment]
Hi, sorry for delay in response.
1) Did you do installation via fresh install from sources or via bg-features-install.sh?
2) When you get this error - is it brand new user from authorized AD group or a user that already exists in Zabbix DB (Administration -> Users)?

 Never seen this error during all tests.

**Comment by BGmot** [comment]
Reproduced and fixed in https://github.com/BGmot/zabbix/commit/40cb365d36daa90a598bb572dbac9aec17cf9948
