### ISSUE TITLE
Curl wasn't working for me

### ISSUE THREAD

**Issue by Maarten-vn** [BGmot/zabbix#14]
edited the curl to

curl -L -o bg-features-install.sh https://raw.githubusercontent.com/BGmot/zabbix/release/6.0-bg/bg-scripts/bg-features-install.sh

@BGmot Side note: This also fixed my issue with timelines not showing on latest data graphs. Works fine in 6.0.

**Comment by BGmot** [comment]
Too early. I have not released the tag 6.0.0-bg which sould mean a release. Was dealing with a problem after 5.0 -> 6.0 upgrade, now it is fixed and I'll release later today (need to update README)

**Comment by BGmot** [comment]
Released. Now the link from RERADME should work.

**Comment by tedserreyn** [comment]
and of course as soon as you release, zabbix releases 6.0.1.

you may want to mention that you need zip/unzip installed also.  my test box did not have these installed by default and this caused the application of your script to fail.

Ted Serreyn
Serreyn Network Services, LLC

**Comment by BGmot** [comment]
README updated. Thanks!
