### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by pixelsquared** [BGmot/zabbix#17]
Would you consider adding support for Zabbix using PostgreSQL as the database?

**Comment by BGmot** [comment]
In early days majority of people used MySQL so I did not consider bothering with PostgreSQL. Now we need to gauge somehow the interest in PostgreSQL support to see whether it is worth the time to be spent...

**Comment by BGmot** [comment]
Implemented in https://github.com/BGmot/zabbix/tree/6.0.5-bg give it a try.
