### ISSUE TITLE
Zabbix 6.0.5 Release

### ISSUE THREAD

**Issue by dronenb** [BGmot/zabbix#21]
It seems as though Zabbix 6.0.5 was released today.

**Comment by dronenb** [comment]
I see some stuff was updated, including the README, however, there still is not a 6.0.5-bg tag available.

**Comment by dronenb** [comment]
^Did not intentionally close -_-

**Comment by BGmot** [comment]
Because it is not released yet -(
No tag -> no release... Or maybe I need to think about different branch model.
Having issues to perform a final test as the latest 6.0.5 image comes with Ubuntu 22 (it used to be Ubuntu 20). Hope to finish this tonight.

**Comment by dronenb** [comment]
Ah, yes. I encountered this issue when trying to run the official 6.0-latest-ubuntu Docker image with 6.0.4. Ubuntu 22.04 uses PHP 8.1, which does not work with Zabbix. [According to support](https://support.zabbix.com/browse/ZBX-21113), this may not be working officially until 6.0.6. Not sure why they switched their official images to use 22.04 when they were not ready to do so...

**Comment by BGmot** [comment]
It's working well for Zabbix 6.0.5 as far as I can tell, try it. Don't use -latest tag, use explicit 6.0.5.
I have some side issue realted to testing feature I am implementing in this repo.

**Comment by BGmot** [comment]
LDAP Authentication is broken in 6.0.5 (not related to my project at all) https://support.zabbix.com/browse/ZBX-21150
So my release is on hold for now.

**Comment by BGmot** [comment]
Should be good now https://github.com/BGmot/zabbix/tree/6.0.5-bg
