### ISSUE TITLE
Zabbix 6.0.5 + Google 2FA: Class 'Sonata\\GoogleAuthenticator\\RuntimeException' not found

### ISSUE THREAD

**Issue by roman-moroz** [BGmot/zabbix#22]
Hello.

Zabbix 6.0.5 on Debian 11 environment, no errors during installations but after enabling Google 2FA, i get this when accessing zabbix after username/pw login:

`PHP Fatal error:  Uncaught Error: Class 'Sonata\\GoogleAuthenticator\\RuntimeException' not found in /usr/share/zabbix/gglauth/GoogleQrUrl.php:74\nStack trace:\n#0 /usr/share/zabbix/ggl.php(92): Sonata\\GoogleAuthenticator\\GoogleQrUrl::generate()\n#1 {main}\n  thrown in /usr/share/zabbix/gglauth/GoogleQrUrl.php on line 74`

Googling gave me suggestion to include gglauth/GoogleAuthenticatorInterface.php, but this is already in /usr/share/zabbix/ggl.php:

```
root@monitoring:~# grep ^include_once /usr/share/zabbix/ggl.php
include_once dirname(__FILE__).'/gglauth/FixedBitNotation.php';
include_once dirname(__FILE__).'/gglauth/GoogleAuthenticatorInterface.php';
include_once dirname(__FILE__).'/gglauth/GoogleAuthenticator.php';
include_once dirname(__FILE__).'/gglauth/GoogleQrUrl.php';
root@monitoring:~#
```

Please assist

**Comment by BGmot** [comment]
I will investigate why this exception class is not found but in this case the root case is you have not defined your Zabbix server name (or it is an empty string).
Please change it to any string (without colon ':') in /etc/zabbix/web/zabbix.conf.php.
`$ZBX_SERVER_NAME                = '';`

**Comment by roman-moroz** [comment]
Populating ZBX_SERVER_NAME did the trick. Thank you.

**Comment by BGmot** [comment]
Error reporting should be fixed by https://github.com/BGmot/zabbix/commit/440fa800a40984ce8409925b7f16aeaeeca0f241
Now no need to look into apache/php logs, 2fa errors will be reported in UI, like:
![image](https://user-images.githubusercontent.com/1423807/172751757-9e29d889-8348-4e4e-a0c6-60539afa8191.png)
