### ISSUE TITLE
Zabbix 6.0.5 No image for QR Code

### ISSUE THREAD

**Issue by Thimoty44** [BGmot/zabbix#23]
Good morning, I fresh installed my zabbix in 6.0.5 and installed the Bgmot 2FA Google Authenticator and I got an issue with the plugin for the moment when the page should generate the image of the qr code I don't have the image and this error pop up in the logs :

```
[error] 95370#95370: *2 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/zabbix/include/classes/core/CCookieSession.php on line 194" while reading response header from upstream, client: 77.148.135.21, server: supervision.thimoty.com, request: "POST /setup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "supervision.thimoty.com", referrer: "https://supervision.thimoty.com/setup.php"
2022/06/07 21:34:32 [error] 96103#96103: *48 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: ggl_secret in /usr/share/zabbix/include/classes/api/services/CUser.php on line 405PHP message: PHP Notice:  Undefined index: ggl_enrolled in /usr/share/zabbix/include/classes/api/services/CUser.php on line 412" while reading response header from upstream, client: 77.148.135.21, server: supervision.thimoty.com, request: "GET /ggl.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "supervision.thimoty.com", referrer: "https://supervision.thimoty.com/index.php"
```

I got another server with different version who work quite good :) So I am here to ask help to resolve this issue. Have a nice day guys !

**Comment by BGmot** [comment]
Hi,
these are just "notices" not errors and should not affect image generation.
What exactly are you trying to do? I see setup.php for some reason, it is not related to 2FA at all.
Do you see any other errors in php/apache logs?

**Comment by Thimoty44** [comment]
I just woke up open my server and it worked I don't know why but I try to enrol this time on another computer with firefox, and it worked, maybe a problem with my browser ? I don't really know maybe an issue with my browser the last day I tried with waterflox and brave. What I was trying to do it is to enrol my OTP. So that it is working now but I don't know how really. I didn't see any other error, so i suppose that is probably a problem with my computer or the browser. Thank you for your help by the way. I thought this error was related because it is calling this index : ggl_enrolled. Have a nice day

**Comment by BGmot** [comment]
The notice in php logs is fixed by https://github.com/BGmot/zabbix/commit/d6f426b96f8d2ad9315de7b4bb8b9ed8d75d5fd3
