### ISSUE TITLE
Zabbix 6.2

### ISSUE THREAD

**Issue by danielsilvapereira** [BGmot/zabbix#25]
How to install in zabbix 6.2?

Not found bg-path-6.2.0.zip

**Comment by BGmot** [comment]
It's not ready yet.

**Comment by mehmozh** [comment]
Will it be released soon?

**Comment by BGmot** [comment]
I hope yes.

**Comment by BGmot** [comment]
Released https://github.com/BGmot/zabbix/tree/release/6.2-bg
Note: multiple LDAP servers feature was introduced in 6.2 that lead to delay in release as I have to re-work some of my code and I don't have two different LDAP servers available to one Zabbix instance so I was not able to test if somebody can test please provide feedback.
PS: sorry for delay - was busy with life.
