### ISSUE TITLE
bg-features-install.sh: line 56: bg-scripts/db-rename-columns.sql: No such file or directory

### ISSUE THREAD

**Issue by XSvirusSAFE** [BGmot/zabbix#26]
I have try to apply the updated patch but I keep getting the following error.

bg-features-install.sh: line 56: bg-scripts/db-rename-columns.sql: No such file or directory

Data password is correct as well as the install area.

**Comment by BGmot** [comment]
What version of Zabbix?

**Comment by XSvirusSAFE** [comment]
6.0.6

**Comment by BGmot** [comment]
Crap. The some files were missing from .zip package. Fixed. Please re-download and try again.
My apologies.

**Comment by XSvirusSAFE** [comment]
Will give it a shot. thanks
