### ISSUE TITLE
Undefined variable: db_user

### ISSUE THREAD

**Issue by es-x** [BGmot/zabbix#27]
Hello, affter install script on 6.2.1 version and made all recommendation for configuration groups and ldaps i have error.

`
"PHP message: PHP Notice:  Undefined variable: db_user in /usr/share/zabbix/include/classes/api/services/CUser.php on line 1492PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/zabbix/include/classes/api/services/CUser.php on line 1492PHP message: PHP Notice:  Undefined index: case_sensitive in /usr/share/zabbix/include/classes/ldap/CLdap.php on line 241" while reading response header from upstream, client: IP, server: zabapp, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/zabbix.sock:", host: "zabbix", referrer: "https://zabbix/index.php"`

**Comment by BGmot** [comment]
These are just warning and don't affect functionality. Anyway fixed in 6c6e9b7df8ef9bf0abbc2c1961d91147d79a4ab0 and will release the fix with 6.2.2.
Thanks for reporting!
