### ISSUE TITLE
Undefined index: case_sensitive

### ISSUE THREAD

**Issue by es-x** [BGmot/zabbix#28]
Hello when i 'm trying  log in. I get warning 
Version 6.2.1

`
Undefined index: case_sensitive in /usr/share/zabbix/include/classes/ldap/CLdap.php on line 241" while reading response header from upstream, client: IP, server: zabbix, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/zabbix.sock:", host: "zabbix", referrer: "https://zabbix/index.php"`

**Comment by BGmot** [comment]
Hello,
this is fixed by eabe0f299de8be29b72886c9b65d1cecfbd3bfa5 commit
Will be released with 6.2.2.
