### ISSUE TITLE
A Few questions

### ISSUE THREAD

**Issue by Beeez** [BGmot/zabbix#3]
Is there a reason why this isn't done via a pull request to make this part of the main application? 

How will this work with updates to Zabbix? How will it stay maintained through updates?

**Comment by BGmot** [comment]
>Is there a reason why this isn't done via a pull request to make this part of the main application?
Zabbix does not accept any pull requests.

>How will this work with updates to Zabbix? 
When new version of 5.0.x released I merge all the changes released by Zabbix into this repository, tag it with 5.0.x-bg build new docker image and test.

>How will it stay maintained through updates?
Obviously if you installed Zabbix from packages I suspect any minor version update will erase all the changes made by this repository (except DB changes). Good point! need to test it.

**Comment by Beeez** [comment]
I am getting this after running everything and testing. I am attempting to log in with the same account i tested authentication with in LDAP Settings, and it succeeded. 

Also, For LDAP group name, is this the DN of the group, or just the flat name? 

![image](https://user-images.githubusercontent.com/46723579/90283169-ab81c000-de3d-11ea-9f9b-832d1539086e.png)

**Comment by BGmot** [comment]
It searches through all members of an array 'memberof' attribute, our Windows AD returns records in format:
'CN=<cn_name>,OU=,OU=...etc'
so cn_name in this example must match any LDAP Group name you created.
The screenshot you posted does not actually say 'Authentication failed' which would mean the user who is trying to login is not a member of any LDAP groups configured at Zabbix server. I am curious whether the user gets created - please check Administration -> Users.
Also are you testing integration against Windows AD or OpenLDAP?

**Comment by BGmot** [comment]
Confirmed - an update will wipe changes without touching DB though.
After update you'd need to run again (replacing 5.0.3-bg with correct new version):
```
curl -L -o bg-features-install.sh https://github.com/BGmot/zabbix/raw/5.0.3-bg/bg-scripts/bg-features-install.sh
sudo bg-features-install.sh
```
and all settings stay in place.
