### ISSUE TITLE
6.0.9 released

### ISSUE THREAD

**Issue by DarkCenobyte** [BGmot/zabbix#32]
6.0.9 version has just been released

Also would it be possible to try an automation for release on new versions in the absence of conflict (maybe with Github Actions) or that in the future the feature could be merged in the Zabbix project?

The 2FA is really a must-have especially when you expose Zabbix to the internet

**Comment by BGmot** [comment]
Released https://github.com/BGmot/zabbix/tree/6.0.9.
Sorry for delay.
For the automation I can try but I review any diff you never know what can change in the code. I will set up an alert on every new release and will do my best to release the next day.
