### ISSUE TITLE
file bg-patch-6.0.19.zip seems be corrupted

### ISSUE THREAD

**Issue by Amiri83** [BGmot/zabbix#35]
Hi ,
I get this error on execution of script 

[root@mtnir-zabbix2 1690281536]# wget https://github.com/BGmot/zabbix/blob/release/6.0-bg/bg-patch-6.0.19.zip
--2023-07-25 14:16:18--  https://github.com/BGmot/zabbix/blob/release/6.0-bg/bg-patch-6.0.19.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5870 (5.7K) [text/plain]
Saving to: ‘bg-patch-6.0.19.zip’

bg-patch-6.0.19.zip                        100%[======================================================================================>]   5.73K  --.-KB/s    in 0s      

2023-07-25 14:16:19 (30.7 MB/s) - ‘bg-patch-6.0.19.zip’ saved [5870/5870]

[root@mtnir-zabbix2 1690281536]# unzip bg-patch-6.0.19.zip
Archive:  bg-patch-6.0.19.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

Regards

**Comment by BGmot** [comment]
Hi,
not sure why you want to do `wget` but if you do then you need to use this link 
```
wget https://github.com/BGmot/zabbix/raw/6.0.19-bg/bg-patch-6.0.19.zip
```
the archive is fine.
