### ISSUE TITLE
Not able to switch to DUO or Google auth

### ISSUE THREAD

**Issue by mrowec** [BGmot/zabbix#36]
Hi BGmot,

when I tested docker zabbix 2fa works great. But after running the install script successfully (no err) the new line under Administratorin shows me 2FA but clicking DUO or Google button nothing happened.

Restart apache2 and zabbix services not helped. 

zabbix version:

ii  zabbix-agent                   1:6.0.21-1+debian11            amd64        Zabbix network monitoring solution - agent
ii  zabbix-apache-conf             1:6.0.21-1+debian11            all          Zabbix network monitoring solution - apache configuration for front-end
ii  zabbix-frontend-php            1:6.0.21-1+debian11            all          Zabbix network monitoring solution - PHP front-end
ii  zabbix-release                 1:6.0-3+debian11               all          Zabbix official repository configuration
ii  zabbix-server-mysql            1:6.0.21-1+debian11            amd64        Zabbix network monitoring solution - server (MySQL)
ii  zabbix-sql-scripts             1:6.0.21-1+debian11            all          Zabbix network monitoring solution - sql-scripts

thanks you for the advice

**Comment by BGmot** [comment]
Please check web-server logs for any errors when you click on DUO or Google.
Does selection change when you click on them (do they become grayish)?
Can't really think of anything that would cause this at the moment...

**Comment by mrowec** [comment]
10.212.130.2 - - [05/Oct/2023:08:53:38 +0200] "POST /zabbix.php HTTP/1.1" 200 5765 "https://XXXXXXXXX.XX/zabbix.php?action=twofa.edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
10.212.130.2 - - [05/Oct/2023:08:53:38 +0200] "POST /zabbix.php?action=twofa.edit HTTP/1.1" 200 4876 "https://XXXXXXXXX.XX/zabbix.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
10.212.130.2 - - [05/Oct/2023:08:53:38 +0200] "GET /jsLoader.php?ver=6.0.21&lang=en_US&files%5B0%5D=servercheck.js HTTP/1.1" 304 4500 "https://XXXXXXXXX.XX/zabbix.php?action=twofa.edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
10.212.130.2 - - [05/Oct/2023:08:53:38 +0200] "GET /jsLoader.php?lang=en_US&ver=6.0.21&showGuiMessaging=1 HTTP/1.1" 304 217 "https://XXXXXXXXX.XX/zabbix.php?action=twofa.edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
10.212.130.2 - - [05/Oct/2023:08:53:38 +0200] "POST /zabbix.php?action=notifications.get&sid=1e725f1f104abfb6&output=ajax HTTP/1.1" 200 1078 "https://XXXXXXXXX.XX/zabbix.php?action=twofa.edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

**Comment by BGmot** [comment]
I reproduced the issue only with 6.0 version. Working on investigation and fixing. Please stand by.

**Comment by BGmot** [comment]
Please re-install 6.0.21 starting with
```
curl -L -o bg-features-install.sh https://raw.githubusercontent.com/BGmot/zabbix/6.0.21-bg/bg-scripts/bg-features-install.sh
```
if it works I'll release 6.0.22.

**Comment by mrowec** [comment]
Hello BGmot !

wooow, its works !! U R superhero :) 
Thank you so much
