### ISSUE TITLE
Zabbix 6.4.7

### ISSUE THREAD

**Issue by GBR7114** [BGmot/zabbix#37]
hello, need to install 2FA with google authenticator on zabbix version 6.4.7. feature has been removed after upgrade from 6.4.6. 

Installation procedure from github on the below link is for 6.4.6 script need to be modified to match zabbix version 6.4.7.

Thank you

**Comment by BGmot** [comment]
Released https://github.com/BGmot/zabbix/tree/6.4.7-bg

**Comment by GBR7114** [comment]
Thank you
