### ISSUE TITLE
Zabbix 6.4.8

### ISSUE THREAD

**Issue by GBR7114** [BGmot/zabbix#41]
Hello,

Can you please upgrade 2FA script version from 6.4.7 to 6.4.8.

Thank you

**Comment by BGmot** [comment]
It's released but could not test as Docker image from Zabbix is not available for 6.4.8 yet. Will build my own image later and test. Or if you wish you can test and report here, would be appreciated.

**Comment by BGmot** [comment]
Tested.Works as expected.

**Comment by GBR7114** [comment]
hello,

Tested for here, works fine. Thank you
