### ISSUE TITLE
bg-patch-6.0.28.zip is incomplete

### ISSUE THREAD

**Issue by ShiOis** [BGmot/zabbix#43]
Hi,
Two errors occur when installing 6.0.28.
* "bg-patch-6.0.28.zip" is unzipped to a directory named "bg-scripts".
```
+ cd bg-patch-6.0.28
bg-features-install.sh: line 26: cd: bg-patch-6.0.28: No such file or directory
```
* "CAuditLog.php" is not in the zip file.
```
+ cp CAuditLog.php /usr/share/zabbix/include/classes/api/services/
cp: cannot stat 'CAuditLog.php': No such file or directory
```
best regards

**Comment by BGmot** [comment]
My fork does not change this file so it is mistakenly included in bg-features-install.sh and does not affect anything.
I will fix this cosmetic error.
