### ISSUE TITLE
ZABBIX_INSTALLED_VERSION=6.4.10 does not work

### ISSUE THREAD

**Issue by faveloso** [BGmot/zabbix#45]
Hello, I am trying to install on zabbix 6.4.10 and the zip file does not exist or is corrupt.

![error](https://github.com/BGmot/zabbix/assets/46932093/c348f893-1322-449c-85f5-9d2b86653b21)
 
could you help me please?

**Comment by BGmot** [comment]
Hi,
should be fixed now. Please repeat the procedure downloading installation script again:
```
curl -L -o bg-features-install.sh https://raw.githubusercontent.com/BGmot/zabbix/6.4.10-bg/bg-scripts/bg-features-install.sh
```

**Comment by faveloso** [comment]
> Hi, should be fixed now. Please repeat the procedure downloading installation script again:
> 
> ```
> curl -L -o bg-features-install.sh https://raw.githubusercontent.com/BGmot/zabbix/6.4.10-bg/bg-scripts/bg-features-install.sh
> ```

It works perfect. Thank you so much.
