### ISSUE TITLE
Zabbix 6.0.30 LTS: Error 500

### ISSUE THREAD

**Issue by evandrosantos-fst** [BGmot/zabbix#46]
I have gotten error 500 when selecting the 2FA option in the zabbix frontend, and the same is true for the LDAP option.

I'm using Zabbix 6.0.30 LTS and the database is mysql Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using EditLine wrapp.

**Comment by BGmot** [comment]
Just tested with both PostgreSQL and MySQL, everything works as expected.
Please check Web server logs, there should be complains about 500 error.
