### ISSUE TITLE
How to add a new device if the existing one is lost?

### ISSUE THREAD

**Issue by harshalbulsara** [BGmot/zabbix#6]
I have implemented the code and it is working as expected. However, I am stuck if I ever lost my phone.

I can optionally disable the 2fa and log in to the account. but, once I enable it again it will not ask to re-register the code.

**Comment by tedserreyn** [comment]
Personally using 1Password to store 2fa 

This syncs across all my devices.

**Comment by BGmot** [comment]
I think the whole point of 2FA is security so don't see how it can be 'temporarily' disabled... Have the user who lost the phone talk to Zabbix admin who can do following.
To reset 2FA registration for particular user you'll need to have access to Zabbix database. After connecting to the DB execute:
`update users where username='<username>' set ggl_enrolled=0; `

**Comment by BGmot** [comment]
Instructions added to README.

**Comment by harshalbulsara** [comment]
This is exactly what I was looking for. Thank you for the quick resolution. 

Keep up the good work.

**Comment by tedserreyn** [comment]
Hey I appreciate you coming out with and maintaining these patches.

I may put a fork out there so I can help you maintain it.

Ted Serreyn
