### ISSUE TITLE
500 error for ggl.php

### ISSUE THREAD

**Issue by uldiseihenbergs** [BGmot/zabbix#8]
Hello!
i just tried to install on my Zabbix server 5.0.20 version, install succeeded.
then i enabled Google Authenticator and log out of Admin account. 
then i tried to log in back, i entered user/psw, and them blank page opens, with 500 Error. tried to see on browser console - incorrect JSON.

**Comment by BGmot** [comment]
Hello!
Just tested on fresh 5.0.20 intsall - everything works as expected. Most probably you executed wrong version of bg-features-install.sh script. Pay attention that you need to use 5.0.20-bg in tag name:
`curl -L -o bg-features-install.sh https://github.com/BGmot/zabbix/raw/5.0.20-bg/bg-scripts/bg-features-install.sh`

**Comment by uldiseihenbergs** [comment]
i just checked again, curl command was this:
`curl -L -o bg-features-install.sh https://github.com/BGmot/zabbix/raw/5.0.20-bg/bg-scripts/bg-features-install.sh`
so, looks like it's the same you wrote.
additional info - when i disabled 2FA via mysql command, and logged back in, i noticed some broken items too - my graphs was without descriptions. then i restored /usr/share/zabbix/ from backup, and everything is back and running.
my install is not fresh at all - i'm running zabbix for years, i don't know what was the first installed version.

**Comment by BGmot** [comment]
Can you please take a look at apache/nginx logs? They should have information about 500 error, what caused it.

**Comment by uldiseihenbergs** [comment]
huh, i'm trying to extract some errors, see below, <redacted> values are my replacements.
```
[Mon Feb 21 21:03:38.911060 2022] [php7:notice] [pid 3808] [client <redacted>:43726] PHP Notice:  Undefined variable: twofa_auth in /usr/share/zabbix/app
/controllers/CControllerTwofaUpdate.php on line 55, referer: https://zabbix.<redacted>/zabbix.php?action=twofa.edit
[Mon Feb 21 21:03:38.911394 2022] [php7:notice] [pid 3808] [client <redacted>:43726] PHP Notice:  Trying to access array offset on value of type null in
/usr/share/zabbix/app/controllers/CControllerTwofaUpdate.php on line 55, referer: https://zabbix.<redacted>/zabbix.php?action=twofa.edit
[Mon Feb 21 21:03:56.935298 2022] [php7:notice] [pid 3808] [client <redacted>:43726] PHP Notice:  Undefined variable: twofa_auth in /usr/share/zabbix/app
/controllers/CControllerTwofaUpdate.php on line 55, referer: https://zabbix.<redacted>/zabbix.php?action=twofa.edit
[Mon Feb 21 21:03:56.935323 2022] [php7:notice] [pid 3808] [client <redacted>:43726] PHP Notice:  Trying to access array offset on value of type null in
/usr/share/zabbix/app/controllers/CControllerTwofaUpdate.php on line 55, referer: https://zabbix.<redacted>/zabbix.php?action=twofa.edit
[Mon Feb 21 21:06:22.515773 2022] [php7:notice] [pid 3808] [client <redacted>:43726] PHP Notice:  Undefined index: ggl_secret in /usr/share/zabbix/includ
e/classes/api/services/CUser.php on line 332, referer: https://zabbix.<redacted>/index.php
[Mon Feb 21 21:06:22.515797 2022] [php7:notice] [pid 3808] [client <redacted>:43726] PHP Notice:  Undefined index: ggl_enrolled in /usr/share/zabbix/incl
ude/classes/api/services/CUser.php on line 339, referer: https://zabbix.<redacted>/index.php
[Mon Feb 21 21:06:22.517234 2022] [php7:error] [pid 3808] [client <redacted>:43726] PHP Fatal error:  Uncaught Error: Class 'Sonata\\GoogleAuthenticator\
\RuntimeException' not found in /usr/share/zabbix/gglauth/GoogleQrUrl.php:74\nStack trace:\n#0 /usr/share/zabbix/ggl.php(97): Sonata\\GoogleAuthenticator\\Go
ogleQrUrl::generate()\n#1 {main}\n  thrown in /usr/share/zabbix/gglauth/GoogleQrUrl.php on line 74, referer: https://zabbix.<redacted>/index.php
[Mon Feb 21 21:06:49.447808 2022] [php7:error] [pid 2810] [client <redacted>:43912] PHP Fatal error:  Uncaught Error: Class 'Sonata\\GoogleAuthenticator\
\RuntimeException' not found in /usr/share/zabbix/gglauth/GoogleQrUrl.php:74\nStack trace:\n#0 /usr/share/zabbix/ggl.php(97): Sonata\\GoogleAuthenticator\\Go
ogleQrUrl::generate()\n#1 {main}\n  thrown in /usr/share/zabbix/gglauth/GoogleQrUrl.php on line 74, referer: https://zabbix.<redacted>/index.php
[Mon Feb 21 21:07:58.008427 2022] [php7:error] [pid 3808] [client <redacted>:43990] PHP Fatal error:  Uncaught Error: Class 'Sonata\\GoogleAuthenticator\
\RuntimeException' not found in /usr/share/zabbix/gglauth/GoogleQrUrl.php:74\nStack trace:\n#0 /usr/share/zabbix/ggl.php(97): Sonata\\GoogleAuthenticator\\Go
ogleQrUrl::generate()\n#1 {main}\n  thrown in /usr/share/zabbix/gglauth/GoogleQrUrl.php on line 74, referer: https://zabbix.<redacted>/index.php
[Mon Feb 21 21:09:04.452814 2022] [php7:error] [pid 6055] [client <redacted>:44058] PHP Fatal error:  Uncaught Error: Class 'Sonata\\GoogleAuthenticator\
\RuntimeException' not found in /usr/share/zabbix/gglauth/GoogleQrUrl.php:74\nStack trace:\n#0 /usr/share/zabbix/ggl.php(97): Sonata\\GoogleAuthenticator\\Go
ogleQrUrl::generate()\n#1 {main}\n  thrown in /usr/share/zabbix/gglauth/GoogleQrUrl.php on line 74, referer: https://zabbix.<redacted>/index.php
[Mon Feb 21 21:11:21.957935 2022] [php7:error] [pid 2799] [client <redacted>:44212] PHP Fatal error:  Uncaught Error: Class 'Sonata\\GoogleAuthenticator\
\RuntimeException' not found in /usr/share/zabbix/gglauth/GoogleQrUrl.php:74\nStack trace:\n#0 /usr/share/zabbix/ggl.php(97): Sonata\\GoogleAuthenticator\\Go
ogleQrUrl::generate()\n#1 {main}\n  thrown in /usr/share/zabbix/gglauth/GoogleQrUrl.php on line 74, referer: https://zabbix.<redacted>/
```

**Comment by BGmot** [comment]
That's wonderful. Now I just need to reproduce the rpoblem. What OS version and PHP version do you use?

**Comment by uldiseihenbergs** [comment]
Ubuntu 20.04 with:
```
$ php --version
PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

```

**Comment by BGmot** [comment]
Does your server name contain colon ':'?
Please execute
```
$ grep -r NAME /etc/zabbix/web/zabbix.conf.php 
$ZBX_SERVER_NAME = 'ey-zabbix';
```

**Comment by uldiseihenbergs** [comment]
`$ grep -r NAME /etc/zabbix/web/zabbix.conf.php ` returns nothing.. there are no such variable defined: ZBX_SERVER_NAME
i have these two:
```
$ZBX_SERVER      = "127.0.0.1";
$ZBX_SERVER_PORT = "10051";
```

**Comment by BGmot** [comment]
That's weird. What name do you see under large red Zabbix icon in top left corner of UI? Here it is "Composed installation" as I am trying to reproduce with docker:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/1423807/155318979-55863efb-9d2f-475c-9329-ff8f88f3f90a.png">

**Comment by uldiseihenbergs** [comment]
look at mine:
![image](https://user-images.githubusercontent.com/60253253/155319807-04dd65d3-e65f-40c2-8e90-665c8e7576c2.png)

**Comment by rachelgomez161999** [comment]
Resolve 500 Internal Server Error by following this steps:-

**Step 1:** Debugging the Issue.

**Step 2:** Empty . htaccess File.

**Step 3:** Debug . htaccess Issues.

**Step 4:** Increase PHP Memory Limit.

**Step 5**: Check if the Admin Works.

**Step 6:** Revert Recent Changes.

**Step 7:** Audit Your Plugins/Extensions/Modules.

**Step 8**: Check File Permissions.

**Regards,
Rachel Gomez**

**Comment by BGmot** [comment]
Hmm... you have an empty name! Did you enter any name during initial set up wizard (where you entered all details about connection to DB)?
Anyway try adding following to /etc/zabbix/web/zabbix.conf.php:
`$ZBX_SERVER_NAME = 'my-zabbix';`
after that you should see it in UI at least and 2FA should not give you a 500 error. The name is used to generate bar-code to scan during Google 2FA enrollment.

**Comment by uldiseihenbergs** [comment]
ok, i can try it..
as i wrote, i have very old Zabbix installation, so looks like this $ZBX_SERVER_NAME is/was optional. i have another Zabbix installation at work, i installed it year ago. and i don't see this variable either. so looks like you can't relay on this variable and you should use your own, or, if missing, just ask it in installation process..

**Comment by BGmot** [comment]
It's here for 5.0.20 but empty by default https://github.com/zabbix/zabbix/blob/5.0.20/ui/conf/zabbix.conf.php.example
Let me dig how Zabbix behaves if it is empty.

**Comment by uldiseihenbergs** [comment]
Yes, i just checked my Zabbix instance at work - i see and empty variable too.

**Comment by BGmot** [comment]
Ok, in Zabbix this variable is optional and results in purely visual effects (you'll see your server name in WebUI).
You can either set this variable to anything that does not contain colon ':' or wait for me to fix the code (use some default name if it's empty).

**Comment by BGmot** [comment]
Fixed in https://github.com/BGmot/zabbix/commit/b9bb4677cb6b72a0c6e5bd2e8128620170524189
WIll be released with the next Zabbix version updated.
If you want to apply the fix now please download ui/gglauth/GoogleQrUrl.php file and put it into /usr/share/zabbix/gglauth/: https://github.com/BGmot/zabbix/blob/b9bb4677cb6b72a0c6e5bd2e8128620170524189/ui/gglauth/GoogleQrUrl.php

**Comment by uldiseihenbergs** [comment]
Hi, i just tested my zabbix with $ZBX_SERVER_NAME variable, and google authenticator works just fine.
but i have additional problems. as wrote above, some items are broken in web now.
![image](https://user-images.githubusercontent.com/60253253/155517903-57a3ffab-6aa2-4b65-b444-aa1889df5c71.png)

and my zabbix error log are full of these:
```
[Thu Feb 24 13:41:53.310405 2022] [php7:warn] [pid 232088] [client <reducted>:37342] PHP Warning:  imagettfbbox(): Could not find/open font in /usr/share/zabbix/include/graphs.inc.php on line 584, referer: https://zabbix.<reducted>/screens.php?elementid=20
[Thu Feb 24 13:41:53.310442 2022] [php7:notice] [pid 232088] [client <reducted>:37342] PHP Notice:  Trying to access array offset on value of type bool in /usr/share/zabbix/include/graphs.inc.php on line 587, referer: https://zabbix.<reducted>/screens.php?elementid=20
[Thu Feb 24 13:41:53.310449 2022] [php7:notice] [pid 232088] [client <reducted>:37342] PHP Notice:  Trying to access array offset on value of type bool in /usr/share/zabbix/include/graphs.inc.php on line 587, referer: https://zabbix.<reducted>/screens.php?elementid=20
[Thu Feb 24 13:41:53.310456 2022] [php7:notice] [pid 232088] [client <reducted>:37342] PHP Notice:  Trying to access array offset on value of type bool in /usr/share/zabbix/include/graphs.inc.php on line 588, referer: https://zabbix.<reducted>/screens.php?elementid=20
[Thu Feb 24 13:41:53.310462 2022] [php7:notice] [pid 232088] [client <reducted>:37342] PHP Notice:  Trying to access array offset on value of type bool in /usr/share/zabbix/include/graphs.inc.php on line 588, referer: https://zabbix.<reducted>/screens.php?elementid=20
[Thu Feb 24 13:41:53.310468 2022] [php7:notice] [pid 232088] [client <reducted>:37342] PHP Notice:  Trying to access array offset on value of type bool in /usr/share/zabbix/include/graphs.inc.php on line 589, referer: https://zabbix.<reducted>/screens.php?elementid=20
```
so i needed to change back font line in /include/defines.inc.php file..

so further suggestions:
- don't replace full files, there can be changes in them;
- in install sh file add DB name as variable too, i have no database with built-in name 'zabbix' :)

**Comment by BGmot** [comment]
Thanks for logs!!! I'll definitely take a look in the evening.

**Comment by BGmot** [comment]
DB name is now a vairable.
You are right about defines.inc.php - it can lead to using ttf font that is missing in your system.
Willing to try the latest revision https://github.com/BGmot/zabbix/blob/release/5.0-bg/bg-scripts/bg-features-install.sh ?

**Comment by uldiseihenbergs** [comment]
ok, there are no errors about my graphs now, but i see new ones:
![image](https://user-images.githubusercontent.com/60253253/155569737-d101a866-a51b-4be6-bd0e-a4dfefb2c951.png)

and BTW, do i really need to download this large zip file with whole zabbix every time?

**Comment by BGmot** [comment]
So you ran new script and got these errors???
Looks like lines like
`if [[ ! $(grep ZBX_AUTH_2FA_NONE include/defines.inc.php) ]]; then echo "define('ZBX_AUTH_2FA_NONE',    0);" >> include/defines.inc.php; fi`
did not execute.
Do you have ZBX_AUTH_2FA_NONE in include/defines.inc.php?
I am thinking of not downloading the whole zip file...

**Comment by uldiseihenbergs** [comment]
Yes, i ran the new script and got these errors.
i just checked defines.inc.php, and there are no ZBX_AUTH_2FA_NONE.
defines.inc.php*.bak file is the same size, so looks like no updates.

**Comment by BGmot** [comment]
I don't understand... can you please manually run
`if [[ ! $(grep ZBX_AUTH_2FA_NONE include/defines.inc.php) ]]; then echo "define('ZBX_AUTH_2FA_NONE', 0);" >> include/defines.inc.php; fi
`
it shoudl add 
`define('ZBX_AUTH_2FA_NONE', 0);
`to the end of this file...

**Comment by uldiseihenbergs** [comment]
yes, now i see `define('ZBX_AUTH_2FA_NONE', 0);` at the end of the file

**Comment by uldiseihenbergs** [comment]
i see your error:
you are already in include subfolder, but your are searching again in include/defines.inc.php
```
cd include
cp ${ZABBIX_INSTALL_PATH}/include/defines.inc.php ${ZABBIX_INSTALL_PATH}/include/defines.inc.php-`date +%s`.bak
if [[ ! $(grep ZBX_AUTH_2FA_NONE include/defines.inc.php) ]]; then echo "define('ZBX_AUTH_2FA_NONE',    0);" >> include/defines.inc.php; fi
if [[ ! $(grep ZBX_AUTH_2FA_DUO include/defines.inc.php) ]]; then echo "define('ZBX_AUTH_2FA_DUO',    1);" >> include/defines.inc.php; fi
if [[ ! $(grep ZBX_AUTH_2FA_GGL include/defines.inc.php) ]]; then echo "define('ZBX_AUTH_2FA_GGL',    2);" >> include/defines.inc.php; fi
if [[ ! $(grep AUDIT_RESOURCE_AD_GROUP include/defines.inc.php) ]]; then echo "define('AUDIT_RESOURCE_AD_GROUP',    100);" >> include/defines.inc.php; fi

```

**Comment by BGmot** [comment]
It's not an error. I found that not all shells understand [[ ]], please test the latest version of the script, it should add these constants to include/defines.inc.php only if they are not there already.

**Comment by uldiseihenbergs** [comment]
sorry, no changes. still missing these variables.

**Comment by BGmot** [comment]
what do you get when you execute from terminal window (as root) from /usr/share/zabbix folder:
```
if [ -z "$(grep ZBX_AUTH_2FA_NONE include/defines.inc.php)" ]; then echo "define('ZBX_AUTH_2FA_NONE', 0);" >> include/defines.inc.php; fi
grep ZBX_AUTH_2FA_NONE include/defines.inc.php
```

**Comment by uldiseihenbergs** [comment]
as expected:
`define('ZBX_AUTH_2FA_NONE', 0);`

**Comment by BGmot** [comment]
God I am stupid... full path needs to be used. Please try https://github.com/BGmot/zabbix/blob/e8c3bfb614a78754ba344a62c4677430d5446c5b/bg-scripts/bg-features-install.sh

**Comment by uldiseihenbergs** [comment]
OK, no more errors for now.

**Comment by uldiseihenbergs** [comment]
another question as i see on other closed issue is zabbix updates - i should run your script every time when upgrade occurs,
if zabbix is updated, and i did't run your script - can i login then?

**Comment by BGmot** [comment]
If Zabbix updated 2FA functionality disappears from authentication process and from Administration menu however all the data stays in tact in the DB so when you run my script you are back in business with all users registered with 2FA not having to do the enrollment again.
Thanks a lot for your help in troubleshooting these issues!

**Comment by uldiseihenbergs** [comment]
OK, when i run your script again, then it's fine. but my question was a bit different: before i run your script on updated zabbix server, can i login or must i disable 2FA via db script to login? then i run your script again, and all should be fine?
i know, it's a bit challenge with updates, but looks like no other options are available at now..

**Comment by BGmot** [comment]
Yes, you can login without running my script. Whatever method of authentication you have configured (internal, LDAP,...) will work.

**Comment by uldiseihenbergs** [comment]
thanks for that, and for your hard work.
i'm closing this issue as completed ;)

**Comment by BGmot** [comment]
Also: now only an archive of patched files will be downloaded.
